export const categoriesData = [
  { name: "Arcade", active: false },
  { name: "Action", active: false },
  { name: "sports", active: false },
  { name: "Action", active: false },
  { name: "Arcade2", active: false },
  { name: "Action2", active: false },
  { name: "sports2", active: false },
  { name: "Action3", active: false },
  { name: "Arcade3", active: false },
  { name: "Adventure", active: true },
  { name: "Action3", active: false },
  { name: "sports3", active: false },
  { name: "Action4", active: false },
  { name: "Arcade4", active: false },
  { name: "Action5", active: false },
  { name: "sports5", active: false },
  { name: "Action6", active: false },
];
